sudo: required

language: node_js
node_js:
  - "5"
  - "5.1"

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull frissdiegurke/sit
  - docker run -p 3000:3000 frissdiegurke/sit

