sudo: required

language: node_js

node_js:
  - "5"
  - "5.1"

services:
  - docker

env:
  - REP=frissdiegurke/sit

before_script: cd app

script: npm test

after_script: cd ..

before_deploy:
  - TAG=`git rev-parse --short HEAD`
  - docker build -t ${REP}:${TAG} .
  - docker tag ${REP}:${TAG} ${REP}:latest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - docker push ${REP}:${TAG}
  - docker push ${REP}:latest

